#!/usr/bin/env python3
"""
Derive the ARR Ready Reckoner's expanded time-horizon table from the IPCC
AR6 WG1 Chapter 4 "assessed GSAT projections" dataset.

WHAT THIS IS
------------
This script is the full, auditable derivation behind the 5 extra time
horizons ("2011-2030", "2031-2050", "2051-2070", "2061-2080", "2071-2090")
added to `TEMPERATURE_PROJECTIONS` in the app's `reckoner.R` on 2026-09-17.
It is *not* part of the deployed Shiny app and has no runtime dependency
on it -- `reckoner.R` only ever contains the plain numeric result of
running this script once. Keep this script (and a copy of the IPCC data
repo it reads from) in version control next to the app so the numbers in
`reckoner.R` are traceable back to their source, without the app itself
needing a NetCDF library or network access at runtime.

DATA SOURCE
-----------
IPCC-WG1/Chapter-4_Figure4.11 (https://github.com/IPCC-WG1/Chapter-4_Figure4.11)
-- the code + data repository behind IPCC AR6 WGI Figure 4.11 and the
"assessed GSAT projections" (Global Surface Air Temperature) referenced in
Chapter 4 / Cross-Chapter Box 4.1. This is also the ultimate source of
ARR's own Table 1.6.2 (the 3 time horizons ARR itself publishes).

Clone or copy that repository somewhere on disk (e.g. as a sibling folder
of this one) and point --ipcc-repo at it; the only files this script
reads are the 5 NetCDF files under its assessed_GSAT_projections/ folder:

    assessed_GSAT_projections/assessed_GSAT_ssp119.nc
    assessed_GSAT_projections/assessed_GSAT_ssp126.nc
    assessed_GSAT_projections/assessed_GSAT_ssp245.nc
    assessed_GSAT_projections/assessed_GSAT_ssp370.nc
    assessed_GSAT_projections/assessed_GSAT_ssp585.nc

Each file's `time` dimension is the *start* year of a rolling 20-year mean
window (confirmed from the file's own metadata: "time axis: 20-year means,
year indicates first year of 20-year window"), with `Q05`/`Q50`/`Q95`
giving that window's 5th/median/95th percentile GSAT anomaly, on a
1995-2014 baseline.

METHOD
------
1. Read Q05/Q50/Q95 for the 8 rolling 20-year windows this app uses
   (2011-2030 through 2081-2100) from each of the 5 SSP files.
2. ARR's Table 1.6.2 is on a *different* baseline (1961-1990, per ARR
   v4.2), and only publishes 3 of these 8 windows (2021-2040, 2041-2060,
   2081-2100), for 4 of the 5 SSPs (no SSP1-1.9). Rather than assume a
   textbook baseline-conversion constant, this script *fits* one: it
   compares this dataset's own raw values for those 3 published windows
   against ARR's already-published numbers (36 data points: 4 scenarios x
   3 windows x 3 percentiles) and solves for the best-fit constant, done
   separately per percentile (a baseline shift should not depend on
   scenario or percentile, so a single per-percentile constant --
   deliberately not per-scenario, not per-window -- is the right amount of
   freedom to allow; fitting less than that failed to reproduce ARR's
   numbers as closely, fitting more risked overfitting 3 windows' worth of
   rounding noise).
3. Reports the fit residuals (how well the fitted offset reproduces ARR's
   own 36 published values) as a check on both the fit and on this being
   the right data source in the first place.
4. Applies the same fitted offset to all 8 windows (all 5 SSPs, though the
   deployed app only uses 4 -- SSP1-1.9 is included here for completeness
   and future use) and rounds to 1 decimal place, matching ARR's own
   published precision.
5. Writes the result as both a CSV (for easy review/diffing) and as a
   ready-to-paste R snippet in the exact shape of `TEMPERATURE_PROJECTIONS`
   in reckoner.R.

USAGE
-----
    pip install netCDF4          # only needed to run this script, not the app
    python3 derive_time_horizons.py --ipcc-repo /path/to/Chapter-4_Figure4.11

Outputs (written next to this script, or to --out-dir):
    derived_time_horizons.csv   -- every (scenario, window, percentile) value,
                                    both raw and offset-adjusted, plus which
                                    windows are new vs. already ARR-published
    derived_time_horizons.R     -- ready-to-paste TEMPERATURE_PROJECTIONS
                                    R snippet (for the 5 *new* windows only --
                                    ARR's 3 published windows are deliberately
                                    left as literals in reckoner.R, not
                                    regenerated by this script, so a future
                                    re-run can never silently drift them)

Re-running this script against a future revision of the IPCC dataset (e.g.
if the assessment is updated) will refit the offset and can flag drift: if
FIT_RESIDUAL_MAX below grows much beyond ~0.06 degC, treat that as a signal
the dataset or ARR's table has changed and re-review before trusting the
new numbers.
"""

import argparse
import csv
import datetime
import statistics
import sys
from pathlib import Path

try:
    import netCDF4
except ImportError:
    sys.exit(
        "This script needs the netCDF4 Python package (not required by the "
        "deployed app itself). Install with:\n\n"
        "    pip install netCDF4 --break-system-packages\n"
    )

# ---------------------------------------------------------------------------
# ARR v4.2 Table 1.6.2, exactly as already hardcoded in reckoner.R.
# These are the ground truth this script's fit is checked against -- never
# derived, never overwritten by this script.
# ---------------------------------------------------------------------------
ARR_PUBLISHED = {
    "SSP1-2.6": {
        "2021-2040": {"5th": 0.9, "median": 1.2, "95th": 1.5},
        "2041-2060": {"5th": 1.0, "median": 1.4, "95th": 1.9},
        "2081-2100": {"5th": 1.0, "median": 1.5, "95th": 2.1},
    },
    "SSP2-4.5": {
        "2021-2040": {"5th": 0.9, "median": 1.2, "95th": 1.5},
        "2041-2060": {"5th": 1.3, "median": 1.7, "95th": 2.2},
        "2081-2100": {"5th": 1.8, "median": 2.4, "95th": 3.2},
    },
    "SSP3-7.0": {
        "2021-2040": {"5th": 0.9, "median": 1.2, "95th": 1.5},
        "2041-2060": {"5th": 1.4, "median": 1.8, "95th": 2.3},
        "2081-2100": {"5th": 2.5, "median": 3.3, "95th": 4.3},
    },
    "SSP5-8.5": {
        "2021-2040": {"5th": 1.0, "median": 1.3, "95th": 1.6},
        "2041-2060": {"5th": 1.6, "median": 2.1, "95th": 2.7},
        "2081-2100": {"5th": 3.0, "median": 4.1, "95th": 5.4},
    },
}

# Maps this app's scenario labels to the IPCC repo's SSP file suffixes.
# ssp119 is read too (for completeness) even though the app doesn't offer
# a "SSP1-1.9" scenario option.
SSP_FILES = {
    "SSP1-2.6": "ssp126",
    "SSP2-4.5": "ssp245",
    "SSP3-7.0": "ssp370",
    "SSP5-8.5": "ssp585",
    "SSP1-1.9 (not used by the app)": "ssp119",
}

# All 8 rolling 20-year windows this app's TIME_HORIZON_OPTIONS covers,
# identified by their end year (window = end-19 .. end).
ALL_WINDOW_END_YEARS = [2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100]
ARR_PUBLISHED_WINDOWS = {"2021-2040", "2041-2060", "2081-2100"}
PERCENTILES = ["5th", "median", "95th"]
NC_VAR_FOR_PCT = {"5th": "Q05", "median": "Q50", "95th": "Q95"}

# Fit residuals well inside ARR's own 0.1 degC rounding are expected; a much
# larger max residual means something changed and should not be trusted
# blindly (see the FIT_RESIDUAL_MAX check at the end of main()).
FIT_RESIDUAL_WARN_THRESHOLD = 0.10


def load_windows(nc_path: Path) -> dict:
    """Read one SSP's NetCDF file and return {"start-end": {"5th":..,
    "median":.., "95th":..}} for every window this app needs."""
    ds = netCDF4.Dataset(nc_path)
    time_units = ds.variables["time"].units
    if not time_units.startswith("days since "):
        raise ValueError(f"Unexpected time units in {nc_path}: {time_units}")
    epoch = datetime.date.fromisoformat(time_units.removeprefix("days since ").split(" ")[0])
    start_years = [(epoch + datetime.timedelta(days=int(d))).year for d in ds.variables["time"][:]]

    windows = {}
    for end in ALL_WINDOW_END_YEARS:
        start = end - 19
        if start not in start_years:
            raise ValueError(f"{nc_path.name}: no window starting {start} (needed for {start}-{end})")
        idx = start_years.index(start)
        windows[f"{start}-{end}"] = {
            pct: float(ds.variables[NC_VAR_FOR_PCT[pct]][idx]) for pct in PERCENTILES
        }
    ds.close()
    return windows


def fit_offset(raw: dict) -> dict:
    """Fit one additive offset per percentile by comparing `raw` (this
    dataset's own values) against ARR_PUBLISHED for the 3 windows ARR
    already publishes. Returns {"5th": offset, "median": offset, "95th": offset}."""
    diffs = {"5th": [], "median": [], "95th": []}
    for scenario, windows in ARR_PUBLISHED.items():
        for window, pcts in windows.items():
            for pct, arr_val in pcts.items():
                diffs[pct].append(arr_val - raw[scenario][window][pct])
    return {pct: statistics.mean(vals) for pct, vals in diffs.items()}


def check_fit_residuals(raw: dict, offsets: dict) -> float:
    """Print a residual table (ARR published vs. offset-adjusted raw value
    for the 3 already-published windows) and return the max abs residual."""
    print("\nFit check -- ARR's own 3 published windows vs. this dataset + fitted offset:")
    print(f"{'scenario':10s} {'window':10s} {'pct':6s} {'ARR':>6s} {'fitted':>8s} {'resid':>7s}")
    max_resid = 0.0
    for scenario, windows in ARR_PUBLISHED.items():
        for window, pcts in windows.items():
            for pct, arr_val in pcts.items():
                fitted = raw[scenario][window][pct] + offsets[pct]
                resid = fitted - arr_val
                max_resid = max(max_resid, abs(resid))
                print(f"{scenario:10s} {window:10s} {pct:6s} {arr_val:6.2f} {fitted:8.3f} {resid:+7.3f}")
    print(f"\nmax abs residual: {max_resid:.3f} degC "
          f"({'OK, within' if max_resid <= FIT_RESIDUAL_WARN_THRESHOLD else 'ABOVE'} "
          f"the {FIT_RESIDUAL_WARN_THRESHOLD:.2f} degC warn threshold)")
    return max_resid


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ipcc-repo", type=Path, required=True,
                         help="Path to a local clone/copy of IPCC-WG1/Chapter-4_Figure4.11 "
                              "(must contain assessed_GSAT_projections/*.nc)")
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).parent,
                         help="Where to write derived_time_horizons.csv / .R (default: this script's folder)")
    args = parser.parse_args()

    nc_dir = args.ipcc_repo / "assessed_GSAT_projections"
    if not nc_dir.is_dir():
        sys.exit(f"Expected {nc_dir} to exist (assessed_GSAT_projections/ under --ipcc-repo).")

    raw = {}
    for scenario, ssp in SSP_FILES.items():
        nc_path = nc_dir / f"assessed_GSAT_{ssp}.nc"
        if not nc_path.exists():
            sys.exit(f"Missing {nc_path}")
        raw[scenario] = load_windows(nc_path)

    offsets = fit_offset(raw)
    print("Fitted per-percentile baseline offsets (1995-2014 -> 1961-1990 basis):")
    for pct in PERCENTILES:
        print(f"  {pct:6s}: {offsets[pct]:+.3f} degC")

    max_resid = check_fit_residuals(raw, offsets)

    # Build the final table: ARR's own literal values for its 3 published
    # windows (never touched), offset-adjusted raw values for the 5 new ones.
    final = {}
    for scenario in raw:
        final[scenario] = {}
        for end in ALL_WINDOW_END_YEARS:
            start = end - 19
            window = f"{start}-{end}"
            is_new = window not in ARR_PUBLISHED_WINDOWS
            if is_new:
                final[scenario][window] = {
                    pct: round(raw[scenario][window][pct] + offsets[pct], 1) for pct in PERCENTILES
                }
            else:
                final[scenario][window] = ARR_PUBLISHED.get(scenario, {}).get(window)

    args.out_dir.mkdir(parents=True, exist_ok=True)

    csv_path = args.out_dir / "derived_time_horizons.csv"
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["scenario", "window", "percentile", "raw_nc_value_1995_2014_baseline",
                    "fitted_offset", "final_value_1961_1990_baseline", "source"])
        for scenario in raw:
            for end in ALL_WINDOW_END_YEARS:
                start = end - 19
                window = f"{start}-{end}"
                is_new = window not in ARR_PUBLISHED_WINDOWS
                for pct in PERCENTILES:
                    rawval = raw[scenario][window][pct]
                    finalval = final[scenario][window][pct] if final[scenario][window] else ""
                    source = "derived (this script)" if is_new else "ARR Table 1.6.2 (published, untouched)"
                    w.writerow([scenario, window, pct, f"{rawval:.4f}", f"{offsets[pct]:+.4f}", finalval, source])
    print(f"\nWrote {csv_path}")

    r_path = args.out_dir / "derived_time_horizons.R"
    new_windows_in_order = [f"{e-19}-{e}" for e in ALL_WINDOW_END_YEARS if f"{e-19}-{e}" not in ARR_PUBLISHED_WINDOWS]
    with open(r_path, "w") as f:
        f.write("## Auto-generated by derive_time_horizons.py -- do not hand-edit.\n")
        f.write("## Paste these entries into TEMPERATURE_PROJECTIONS in reckoner.R,\n")
        f.write("## alongside (not replacing) ARR's own 3 published time-horizon entries.\n")
        f.write(f"## Regenerate with: python3 derive_time_horizons.py --ipcc-repo <path>\n")
        f.write(f"## Max fit residual against ARR's published values this run: {max_resid:.3f} degC\n\n")
        for scenario in ["SSP1-2.6", "SSP2-4.5", "SSP3-7.0", "SSP5-8.5"]:
            f.write(f"# {scenario} -- new entries only (ARR's own 3 published entries unchanged in reckoner.R)\n")
            for window in new_windows_in_order:
                v = final[scenario][window]
                f.write(
                    f'"{window}" = c("5th percentile" = {v["5th"]}, '
                    f'"median" = {v["median"]}, "95th percentile" = {v["95th"]}),\n'
                )
            f.write("\n")
    print(f"Wrote {r_path}")

    if max_resid > FIT_RESIDUAL_WARN_THRESHOLD:
        print(
            f"\nWARNING: max fit residual ({max_resid:.3f} degC) exceeds the "
            f"{FIT_RESIDUAL_WARN_THRESHOLD:.2f} degC warn threshold used when this was first "
            "derived. Review before trusting the new numbers -- the dataset or ARR's table may "
            "have changed.",
            file=sys.stderr,
        )
        sys.exit(2)


if __name__ == "__main__":
    main()
