## Auto-generated by derive_time_horizons.py -- do not hand-edit.
## Paste these entries into TEMPERATURE_PROJECTIONS in reckoner.R,
## alongside (not replacing) ARR's own 3 published time-horizon entries.
## Regenerate with: python3 derive_time_horizons.py --ipcc-repo <path>
## Max fit residual against ARR's published values this run: 0.060 degC

# SSP1-2.6 -- new entries only (ARR's own 3 published entries unchanged in reckoner.R)
"2011-2030" = c("5th percentile" = 0.8, "median" = 1.0, "95th percentile" = 1.2),
"2031-2050" = c("5th percentile" = 1.0, "median" = 1.3, "95th percentile" = 1.7),
"2051-2070" = c("5th percentile" = 1.1, "median" = 1.5, "95th percentile" = 2.0),
"2061-2080" = c("5th percentile" = 1.1, "median" = 1.5, "95th percentile" = 2.0),
"2071-2090" = c("5th percentile" = 1.0, "median" = 1.5, "95th percentile" = 2.1),

# SSP2-4.5 -- new entries only (ARR's own 3 published entries unchanged in reckoner.R)
"2011-2030" = c("5th percentile" = 0.8, "median" = 1.0, "95th percentile" = 1.2),
"2031-2050" = c("5th percentile" = 1.1, "median" = 1.4, "95th percentile" = 1.8),
"2051-2070" = c("5th percentile" = 1.4, "median" = 1.9, "95th percentile" = 2.5),
"2061-2080" = c("5th percentile" = 1.5, "median" = 2.1, "95th percentile" = 2.7),
"2071-2090" = c("5th percentile" = 1.7, "median" = 2.2, "95th percentile" = 3.0),

# SSP3-7.0 -- new entries only (ARR's own 3 published entries unchanged in reckoner.R)
"2011-2030" = c("5th percentile" = 0.8, "median" = 1.0, "95th percentile" = 1.1),
"2031-2050" = c("5th percentile" = 1.2, "median" = 1.5, "95th percentile" = 1.9),
"2051-2070" = c("5th percentile" = 1.7, "median" = 2.2, "95th percentile" = 2.8),
"2061-2080" = c("5th percentile" = 1.9, "median" = 2.5, "95th percentile" = 3.3),
"2071-2090" = c("5th percentile" = 2.2, "median" = 2.9, "95th percentile" = 3.8),

# SSP5-8.5 -- new entries only (ARR's own 3 published entries unchanged in reckoner.R)
"2011-2030" = c("5th percentile" = 0.8, "median" = 1.0, "95th percentile" = 1.2),
"2031-2050" = c("5th percentile" = 1.3, "median" = 1.7, "95th percentile" = 2.1),
"2051-2070" = c("5th percentile" = 1.9, "median" = 2.6, "95th percentile" = 3.3),
"2061-2080" = c("5th percentile" = 2.2, "median" = 3.0, "95th percentile" = 4.0),
"2071-2090" = c("5th percentile" = 2.6, "median" = 3.5, "95th percentile" = 4.7),

